{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "customer.serviceAccountName" . }}
  labels:
{{ include "customer.labels" . | indent 4 }}
{{- end -}}